---
- name: Security Hardening and Updates
  hosts: lanhosts
  become: yes
  gather_facts: yes

  tasks:
    - name: Install security updates only
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        only_upgrade: yes
      when: ansible_facts['os_family'] == 'Debian'
      register: security_updates

    - name: Install unattended-upgrades package
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Configure automatic security updates
      ansible.builtin.copy:
        content: |
          Unattended-Upgrade::Automatic-Reboot "false";
          Unattended-Upgrade::Automatic-Reboot-Time "02:00";
          Unattended-Upgrade::DevRelease "false";
          Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          Unattended-Upgrade::Mail "root";
          Unattended-Upgrade::MailReport "on-change";
          Unattended-Upgrade::SyslogEnable "true";
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: '0644'
      when: ansible_facts['os_family'] == 'Debian'

    - name: Enable automatic security updates
      ansible.builtin.copy:
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "7";
          APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: '0644'
      when: ansible_facts['os_family'] == 'Debian'

    - name: Display security update results
      ansible.builtin.debug:
        msg: "Security updates applied: {{ 'Yes' if security_updates.changed else 'No updates available' }}"
      when: ansible_facts['os_family'] == 'Debian' 